# Page settings

baseURL = "https://elias.fahssi.ca/resume/"
languageCode = "en"
title = "Elias Fahssi | Strategist, marketer, product person"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"






[params]
    author = "Elias Fahssi"
    description = "Elias' resume"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Elias Fahssi"
        tagline = "Product Marketing + GTM Strategy"
        avatar = "avatar2.png"







    [params.contact]
        enable = true
        location = "Calgary, Alberta, Canada"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        text = "403 470 1131"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:elias@fahssi.ca"
        text = "elias@fahssi.ca"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://elias.fahssi.ca"
        text = "elias.fahssi.ca"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "GTM strategy and positioning for new products"
        [[params.skills.list.items]]
        details = "Launch leadership"
        [[params.skills.list.items]]
        details = "Market research and competitive intelligence"
        [[params.skills.list.items]]
        details = "Sales enablement"
        [[params.skills.list.items]]
        details = "Channel management and rep engagement"
        [[params.skills.list.items]]
        details = "Segmentation and personas"
        [[params.skills.list.items]]
        details = "User interviews"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Certificate in Product Strategy"
        university = "Northwestern University"
        dates = "2021"
        [[params.education.list]]
        degree = "MPhil in English Language"
        university = "University of Glasgow"
        dates = "2012 - 2014"
        [[params.education.list]]
        degree = "BA in English Literature"
        university = "Mount Royal University"
        dates = "2008 - 2012"








    [params.presentations]
        enable = true

        [[params.presentations.list]]
        name = "Arts Education in the 21st Century"
        body = "Mount Royal University Board of Governors"
        date = "2022"
        [[params.presentations.list]]
        name = "Manufacturing Meaning: Modern and Medieval Material Sustainability?"
        body = "University of Calgary Graduate College"
        date = "2018"
        [[params.presentations.list]]
        name = "Calgary, Carbon, and Components: Opportunities for Passive House"
        body = "International Passive House Conference"
        date = "2018"
        








    [params.languages]
        enable = false

        [[params.languages.list]]
        name = "English"
        level = "Native"
        [[params.languages.list]]
        name = "Spanish"
        level = "Professional"








    [params.interests]
        enable = false

        [[params.interests.list]]
        name = "Climbing"
        [[params.interests.list]]
        name = "Snowboarding"
        [[params.interests.list]]
        name = "Photography"
        [[params.interests.list]]
        name = "Travelling"








    [params.summary]
        enable = true
        text = "8+ years of experience in B2B product marketing, strategy, and go-to-market. Educator at heart who loves training, enablement, and getting people where they want to go. Strong industry experience in construction, architecture and design, manufacturing, and design software. Curious and collaborative leader confident building from the ground up. Track record of elevating commercial teams through creativity, research, and a customer-first lens."








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Manager, GTM Strategy"
        dates = "2022 - 2023"
        company = "DIRTT"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem."
        [[params.experience.list.items]]
        details = "Implemented a tiered product release framework and commercial launch process"
        [[params.experience.list.items]]
        details = "Partnered with teams across the organization to develop commercial priorities (OKRs)."
        [[params.experience.list.items]]
        details = "Ran customer engagement initiatives and competitive intelligence to inform product strategy."

        [[params.experience.list]]
        title = "Program Lead, Strategic Marketing"
        dates = "2021 - 2022"
        company = "DIRTT"
        details = "This program supported a brand refresh, and focused on positioning the company as the category leader for industrialized construction. We ran 2 themed-campaigns targeting Healthcare and Commercial segments, and built evergreen sales tools to support cross-selling. I had budget ownership and coordinated with subject matter teams to support strategic initiatives around conferences, events, and speaking opportunities. The highlight was launching a new public website and presenting new sales training to our rep and partner teams across North America. "
        [[params.experience.list.items]]
        details = "Refreshed the CEU program and launched a new course with industry partner Thinklab."
        [[params.experience.list.items]]
        details = "Programmed case studies and project profiles to amplify campaign themes."
        [[params.experience.list.items]]
        details = "Wrote internal and external \"points-of-view\" on products and market segments."

        [[params.experience.list]]
        title = "Strategist, Product Marketing"
        dates = "2019 - 2021"
        company = "DIRTT"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."
        [[params.experience.list.items]]
        details = "Led the product launch for Inspire, the company's newest glass wall system, targeted for the commercial segment and design-forward architects."
        [[params.experience.list.items]]
        details = "Executed a renaming and soft relaunch of the cabinet portfolio to capitalize on a new industry standard and changing market perceptions around customization."
        [[params.experience.list.items]]
        details = "Delivered regular rep and partner onboarding, 1:1 training, and participated as a SME on sales and project calls."       


        [[params.experience.list]]
        title = "Product Expert, Timber Frame"
        dates = "2015 - 2019"
        company = "DIRTT"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."
        [[params.experience.list.items]]
        details = "Lead the market introduction of a new business line and acted as expert and single point of contact."    
        [[params.experience.list.items]]
        details = "Developed core operations principles and procedures, such as pricing and quoting, phases of design, CAD drawing standards, and project delivery." 
        [[params.experience.list.items]]
        details = "Delivered hundreds of on-site client tours of our manufacturing facility and design experience centre." 

        [[params.experience.list]]
        title = "Specialist Government Contracts"
        dates = "2014 - 2015"
        company = "DIRTT"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."
        [[params.experience.list.items]]
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit."   

        [[params.experience.list]]
        title = "Coordinator, Shipping"
        dates = "2013 - 2014"
        company = "DIRTT"
        details = "Worked with factory production teams to ship "
        [[params.experience.list.items]]
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."











    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Collaborator, Phoenix Rising Engagement Series"
        meta = "Mount Royal University"
        tagline = "Public engagements celebrating research and teaching in the Humanities, Social Sciences, and Creative Arts. "

        [[params.projects.list]]
        title = "Researcher, The Cotton Nero A.x. Project"
        meta = "University of Calgary & British Library"
        tagline = "Multi-disciplinary project focused on photographing, transcribing, editing, and publishing 4 poems from a hand-written Middle English manuscript."

     










    [params.information]
        enable = true

        [[params.information.list]]
        title = "Volunteering"
        [[params.information.list.items]]
        details = "2019 - 2022 · Canadian Society of Medievalists, Webmaster"
        [[params.information.list.items]]
        details = "2017 - 2020 · Calgary Public Library, Architectural Tour Guide"
        [[params.information.list.items]]
        details = "2017 - 2019 · Mount Royal University, Student Mentor"

        [[params.information.list]]
        title = "Interests"
        details = "Soccer, Skiing, Reading, Stationery, Puzzles"








    [params.social]
        enable = false

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/username"
        title = "username"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/username"
        title = "username"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/username"
        title = "@username"




